### ISSUE TITLE
Get/set model results (mutators)

### ISSUE THREAD

**Issue by kvlknctk** [hagopj13/node-express-mongoose-boilerplate#14]
Hi, 
I want to wrap image url in schema results. Because I saved my file name as public/x.jpg. 
I need to show url like this : http://localhost:3000/public/x.jpg.

My temprorary bad solution 
```javascript

theaterSchema.methods.transform = function () {
  const theater = this;

  let data = pick(theater.toJSON(), ['id', 'title', 'body', 'image', 'tags']);
  if(!data.image){
    return data;
  }else {
    return Object.assign({}, data, {
      image: 'http://localhost:3000/' + data.image
    })
  }

};

```
But I dont set with pagination for new pagination feature. 
I wonder your best practice. 

Best regards.

**Comment by hagopj13** [comment]
@kvlknctk please have a look at the latest version of my code. I removed the `transform` methods from my models (in [f8ba3f6](https://github.com/hagopj13/node-express-mongoose-boilerplate/commit/f8ba3f619ac42f2030c358fb44095b72fb37013b)). They were initially there to clean the data that gets returned (replacing _id with id, removing __v, createdAt and updatedAt).

I now recommend defining the transform method of the toJSON schema option: https://mongoosejs.com/docs/api/document.html#document_Document-toJSON

Your code would look something like
```javascript
theatreSchema.options.toJSON.transform = function (doc, ret, options) {
  if (doc.image) {
    ret.image = `http://localhost:3000/${doc.image}`;
  }
  return ret;
}
```
The nice thing about this way is that you **don't** have to explicitly call `transform()` in the controllers (You should in fact remove it if you are still using it). `toJSON` will be automatically called on the document when sending the response.

**One last tip**:
As mentioned above, I was using the `transform` methods to clean the response data. Now I do that using the toJSON custom plugin. I'm using it in `src/models/user.model.js`. This plugin removes __v, createdAt, updatedAt, and any schema path that has private: true, and also replaces _id with id. Once it is done doing that, it will call the schema toJSON transform method if any (like the one we defined above).
```javascript
const { toJSON, paginate } = require('./plugins');

theatreSchema.options.toJSON.transform = function (doc, ret, options) {
  if (doc.image) {
    ret.image = `http://localhost:3000/${doc.image}`;
  }
  return ret;
}

theatreSchema.plugin(toJSON);
theatreSchema.plugin(paginate);
```

If you defined your schema this way, the transform logic will also work on paginate.

**Comment by kvlknctk** [comment]
you so helpful, thnx.
