### ISSUE TITLE
Relations (Populate)

### ISSUE THREAD

**Issue by kvlknctk** [hagopj13/node-express-mongoose-boilerplate#16]
Hi,

I want to load the relationship with the populate function inside the controller. I also use paginate. 

```javascript
const countPromise = this.countDocuments(filter).exec();
    const docsPromise = this.find(filter).populate('community').sort(sort).skip(skip).limit(limit).exec();
```
.populate('community') 

To do this, I edited the plugin part. But I don't want this to work on all models. how can I define a relationship through the controller?

Best regards.

**Comment by hagopj13** [comment]
@kvlknctk you can modify the paginate plugin options, by adding a populate field. It should of course be optional (like sortBy, limit, and page). then your docsPromise would become: 
```javascript
const docsPromise = this.find(filter).populate(populate).sort(sort).skip(skip).limit(limit).exec();
```
The line above should in fact work even if the populate option is undefined. You can also (preferably) do:
```javascript
let query = this.find(filter).sort(sort).skip(skip).limit(limit);
if (populate) {
  query = query.populate();
}
const docsPromise = query.exec();
```
