### ISSUE TITLE
Why not separate mongoose plugins into a diff repository?

### ISSUE THREAD

**Issue by iagowp** [hagopj13/node-express-mongoose-boilerplate#24]
Also, loved the idea for private fields, but it doesn't work with nested fields. I've made a change on the project I've started from this boilerplate, something like 

```
if (path.includes('.')) {
  const [a, b] = path.split('.');
  delete ret[a][b];
} else {
  delete ret[path];
}
```

it obviously only work for 1 level of nesting, but changing to allow multiple would be fairly easy. Do you think this is something you'd like to see added to the plugin in this repo, or perhaps in a separated package?

**Comment by hagopj13** [comment]
@iagowp thanks for the feedback. I am already thinking about extracting this plugin into a different repo. When I do so, I will also consider private nested fields.
Another thing you could do (for now), is create a model for the sub document and attach the plugin to it as well. Then private fields of the sub document would also be handled correctly.
