### ISSUE TITLE
Swagger UI not adding Authorization to header

### ISSUE THREAD

**Issue by 3bu1** [hagopj13/node-express-mongoose-boilerplate#25]
Hi,
I am trying to access APIs using swagger API, 
Steps i did:
- I have created a user with admin role, i can see data in mongoDb.

- after plain installation I tried to get user but it says
`error: Error: Please authenticate at /src/middlewares/auth.js:10:19`

where is to add the token generated while user login? Thanks.

**Comment by khkmalki** [comment]
I use postman, so I can control the headers of the request. You can do that using CLI.

**Comment by 3bu1** [comment]
@khkmalki Even i am able to do it using postman, But i want it using swagger UI. Thanks

**Comment by FrazCake** [comment]
@3bu1 You can add the token by clicking the Authorize button on the top right corner.
![Schermata 2020-09-09 alle 09 36 38](https://user-images.githubusercontent.com/7004159/92569291-b6831100-f280-11ea-8457-4b5244840dcf.png)

**Comment by hagopj13** [comment]
@FrazCake is right. That's how you would authorize in Swagger UI using your access token.
