### ISSUE TITLE
Reset Password throwing 401 error

### ISSUE THREAD

**Issue by brainwatch** [hagopj13/node-express-mongoose-boilerplate#27]
Hi

Thanks for the crisp boilerplate code orchestration. 

Regarding the Reset Password feature, the API throws unauthorized error. Could you direct me if I'm missing something?

thanks
~ bw

**Comment by hagopj13** [comment]
Hi @brainwatch , you should first call the forgot password API (`POST /v1/auth/forgot-password`) and specify the email address in the body. If the email address is found, an email will be sent to it which contains the reset password token.

You should then call the reset password API and insert the token you got in the email as a query param.
`POST /v1/auth/reset-password?token=insert-token-here`

**Comment by hagopj13** [comment]
Hi @brainwatch , you should first call the forgot password API (`POST /v1/auth/forgot-password`) and specify the email address in the request body. If the email address is found, an email will be sent to it which contains the reset password token.

You should then call the reset password API and insert the token you got in the email as a query param.
`POST /v1/auth/reset-password?token=insert-token-here`
