### ISSUE TITLE
API documentation generation

### ISSUE THREAD

**Issue by hagopj13** [hagopj13/node-express-mongoose-boilerplate#3]
It would be nice if we could create API documentation from certain annotations in the source code

**Comment by austin047** [comment]
How do i help?

**Comment by hagopj13** [comment]
@austin047 thanks for reaching out! I was looking if someone might want to set up automatic documentation generation for the endpoints. Contributions are welcomed.

**Comment by austin047** [comment]
automatic documentation with jsdoc??

**Comment by hagopj13** [comment]
@austin047 jsdoc looks good. It would also be nice if it was done with Swagger (there is a swagger-jsdoc library)

**Comment by austin047** [comment]
Alright. 
I do know about swagger-jsdoc. 

you propose we use that?? 

If in that case we will still have to generate the swagger specification file so developers can have the opportunity of viewing the specifications before it's passed to the swagger UI.

**Comment by hagopj13** [comment]
@austin047 let's go for swagger-jsdoc then

**Comment by hagopj13** [comment]
Closed by #12
