### ISSUE TITLE
Can't Access Swagger UI When It's Behind Proxy

### ISSUE THREAD

**Issue by MRdevX** [hagopj13/node-express-mongoose-boilerplate#30]
Hi,
I'm starting a project on top of this boilerplate, although it's pretty great and helpful. But I have a little problem with swagger UI.
it works fine on my local machine, but when it comes to deployment, swagger UI is not loading, and I get these errors:

![image](https://user-images.githubusercontent.com/13729592/94398217-05caac00-0172-11eb-835e-09e247bc6e46.png)

**Comment by hagopj13** [comment]
What proxy are you using? Where is the browser trying to load these files from? [This](https://stackoverflow.com/questions/59974843/nginx-response-with-404-on-static-resourse-of-swaggerui-express) might be helpful.

**Comment by MRdevX** [comment]
> What proxy are you using? Where is the browser trying to load these files from? [This](https://stackoverflow.com/questions/59974843/nginx-response-with-404-on-static-resourse-of-swaggerui-express) might be helpful.

We are using Nginx, and I'm using my browser on my laptop. the problem is these static files are generated dynamically.
are there any related settings should I put on Nginx config?

**Comment by hagopj13** [comment]
Your problem seems similar to what is described in the link I sent above: https://stackoverflow.com/questions/59974843/nginx-response-with-404-on-static-resourse-of-swaggerui-express
Did you check it?
