### ISSUE TITLE
I want to use Mongo Operators in pagination

### ISSUE THREAD

**Issue by kvlknctk** [hagopj13/node-express-mongoose-boilerplate#32]
Hi,
I want to improve my queries with parameters. I have to send an array through parameters and query accordingly. I did it myself manually, but I wonder how to do this without breaking the structure.

As an example, what I want to do is filter a content that has an array. I have to shoot content that has the values I have specified in this way. The query I made is below

`endpoint?limit=10&page=1&tags[]=foo&tags[]=bar`

When I change the codes in the paginate plugin as follows, what I want to do is exactly. How can I make my query in a simple and beautiful way?
```javascript

 schema.statics.paginate = async function(filter, options) {
  ...
    const countPromise = this.countDocuments(filter).exec();
    const docsPromise = this.find({tags: { $in : ['foo', 'bar'] }} ).populate(options.relations).sort(sort).skip(skip).limit(limit).exec();

```

Thanks.

**Comment by hagopj13** [comment]
@kvlknctk if I understand you correctly, you want to do filtering using the paginate plugin. The `filter` argument is where you would supply the mongo filter.
