### ISSUE TITLE
Auth middleware: httpStatus.FORBIDDEN will never be executed

### ISSUE THREAD

**Issue by gustavopiucco** [hagopj13/node-express-mongoose-boilerplate#40]
Hello, 

I was analyzing the code and apparently the following code will never be executed:

middleware/auth.js
```
if (!hasRequiredRights && req.params.userId !== user.id) {
            return reject(new ApiError(httpStatus.FORBIDDEN, 'Forbidden'));
        }
```

It should be
```
if (!hasRequiredRights || req.params.userId !== user.id) {
            return reject(new ApiError(httpStatus.FORBIDDEN, 'Forbidden'));
        }
```

Or am I wrong? Currently with the && operator the condition will always return false

**Comment by fabiodmf** [comment]
Hi Gustavo,

This logic is to prevent a normal user from viewing / managing another user. Only admins (or another role with the proper rights) should be able to do this; but, at the same time, allow him/her to modify their own information.

**Comment by hagopj13** [comment]
Thank you @fabiodmf for the correct answer
