### ISSUE TITLE
Swagger UI not showing operations

### ISSUE THREAD

**Issue by arkanos** [hagopj13/node-express-mongoose-boilerplate#41]
First of all, thanks for this awesome boilerplate!

I have downloaded the repo in order to check it out and I have found that the operations grouped by tags on Swagger UI are not showing:

![image](https://user-images.githubusercontent.com/6362943/99131738-35475200-2614-11eb-8d55-a65690fc0fa6.png)

When you click on both Auth or Users tags, nothing appears.

This is right after cloning the repo and doing an npm install command.

Not sure if this is related with the configuration (as it seems correct) or the swagger packages. I have tried several browsers with same outcome. No console error message or watsoever.

**Comment by hagopj13** [comment]
@arkanos I tried to reproduce the problem you are facing but couldn't (it's working fine with me).
Generally, when you clone the repo, do `npm install`, and then `cp .env.example .env`, and then `npm run dev`, accessing `http://localhost:3000/v1/docs/` should already open a working documentation.
I have `v 4.1.4` of `swagger-ui-express` and `v 4.2.0` of `swagger-jsdoc` installed. Can you check if you have these versions? Can you also check if you have node v12+?

**Comment by arkanos** [comment]
Hi @hagopj13 , I'm using node version 12.19:

```
PS C:\Users\ruben\Desktop\node-express-mongoose-boilerplate> node -v
v12.19.0
```

And these versions for the swagger packages from package.json out of the box:

```
"passport": "^0.4.0",
    "passport-jwt": "^4.0.0",
    "pm2": "^4.1.2",
    "swagger-jsdoc": "^4.0.0",
    "swagger-ui-express": "^4.1.4",
    "validator": "^13.0.0",
    "winston": "^3.2.1",
    "xss-clean": "^0.1.1"
```

I have updated swagger-jsdoc to 4.2.0 with same results, and even tried mcu to have the latest packages version.

I am currently using Windows, if it might help. I will try on Ubuntu in a few hours and come back to you.

Thanks!

**Comment by hagopj13** [comment]
@arkanos I just tried it on Windows on a new clone of the repo, and faced the same issue. I was able to make it work by doing `yarn install` instead of `npm install`. The project is using `yarn.lock` to lock the dependency versions, and it seems like the problem is occurring when you install using npm.

**Comment by arkanos** [comment]
Wo, did not think about it!

Perfect then, thanks!
