### ISSUE TITLE
Registration bug

### ISSUE THREAD

**Issue by gmdom** [hagopj13/node-express-mongoose-boilerplate#46]
Hi @hagopj13, Thank you for your effort.

I could easily create admin users sending email, password and role to the registration endpoint because it reads the hole body when it only take email and password.

**Comment by fabiodmf** [comment]
Hi @gmdom 

Could you share an example with us? I am unable to reproduce the issue.

```
{
    "code": 400,
    "message": "\"role\" is not allowed"
}
```
Could it be that you have ".unknown (true)," in the registration validation rule? :/

**Comment by gmdom** [comment]
Hi @fabiodmf 

You are right. Thank you
